name: GitHub Pges

on:
  push:
    branches:
      - loki123

jobs:
  deploy:
    runs-on: ubuntu-Latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "20"
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm run build
        - name: Copy Html
          run: cp -a dist/portfolio/browser/index.html dist/portfolio/browser/404.html
        - name: Deploy
          if: success()
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: dist/portfolio/browser
            enable_jekyll: true